# Generated by Django 3.1.7 on 2021-03-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='mainApp.user')),
                ('cut_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut', to='mainApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Basic'), (1, 'Advanced')])),
                ('value', models.IntegerField(choices=[(0, '10 wins'), (1, '5 consecutive wins')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user')),
            ],
        ),
    ]
