# Generated by Django 3.1.7 on 2021-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210518_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='moves',
        ),
        migrations.AddField(
            model_name='game',
            name='edges_configuration',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
