# Generated by Django 3.1.7 on 2021-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_game_player_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='category',
        ),
        migrations.AddField(
            model_name='achievement',
            name='explanation',
            field=models.IntegerField(choices=[(0, 'You have won 10 games in total'), (1, 'You have won 50 games in total'), (2, 'You have won 100 games in total'), (3, 'You have won 5 games in a row, without loosing a single one'), (4, 'You have won 10 games in a row, without loosing a single one'), (5, 'You have won 50 games in a row, without loosing a single one'), (6, 'You have played 50 games in total'), (7, 'You have played 100 games in total'), (8, 'You have played 500 games in total'), (9, 'You have occurred on the first place in rating leaderboard at least once'), (10, 'You have occurred on the second place in rating leaderboard at least once'), (11, 'You have occurred on the third place in rating leaderboard at least once'), (12, 'You have logged in 7 days in a row'), (13, 'You have logged in 14 days in a row'), (14, 'You have logged in 31 days in a row'), (15, 'You have played against 10 different opponents')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='games_lost_as_connect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='games_lost_as_cut',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='games_won_as_connect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='games_won_as_cut',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_achievements',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='value',
            field=models.IntegerField(choices=[(0, '10 wins'), (1, '50 wins'), (2, '100 wins'), (3, '5 consecutive wins'), (4, '10 consecutive wins'), (5, '50 consecutive wins'), (6, '50 games played'), (7, '100 games played'), (8, '500 games played'), (9, '#1 rating'), (10, '#2 rating'), (11, '#3 rating'), (12, '7 days consecutive logins'), (13, '14 days consecutive logins'), (14, '31 days consecutive logins'), (15, 'network builder')]),
        ),
    ]
