# Generated by Django 3.1.7 on 2021-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210527_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consecutive_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='consecutive_logins_max',
            field=models.IntegerField(default=0),
        ),
    ]
